---

cassandra_exporter_version: 2.2.0

cassandra_listen_address: "0.0.0.0"
cassandra_listen_port: "8080"
cassandra_exporter_binary_url: 'https://github.com/criteo/cassandra_exporter/releases/download/{{cassandra_exporter_version}}/cassandra_exporter-{{cassandra_exporter_version}}-all.jar'
cassandra_exporter_config_url: 'https://raw.githubusercontent.com/criteo/cassandra_exporter/master/config.yml'

cassandra_exporter_user: cassandra-exp
cassandra_exporter_group: cassandra-exp

cassandra_exporter_root_dir: /opt/cassandra_exporter
cassandra_exporter_dist_dir: "{{ cassandra_exporter_root_dir }}/dist"
cassandra_exporter_config_dir: "{{ cassandra_exporter_root_dir }}/config"
